/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTrackerRouteImport } from './routes/_auth/tracker'
import { Route as AuthToolsRouteImport } from './routes/_auth/tools'
import { Route as AuthTicketsRouteImport } from './routes/_auth/tickets'
import { Route as AuthTicketParsingRouteImport } from './routes/_auth/ticket-parsing'
import { Route as AuthTelegramRouteImport } from './routes/_auth/telegram'
import { Route as AuthSituationCenterRouteImport } from './routes/_auth/situation-center'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthRegistrationRouteImport } from './routes/_auth/registration'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthMyTicketsRouteImport } from './routes/_auth/my-tickets'
import { Route as AuthCodeRepositoryRouteImport } from './routes/_auth/code-repository'
import { Route as AuthArmDemoRouteImport } from './routes/_auth/arm-demo'
import { Route as AuthArmRouteImport } from './routes/_auth/arm'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthTrackerSplatRouteImport } from './routes/_auth/tracker.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrackerRoute = AuthTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthRoute,
} as any)
const AuthToolsRoute = AuthToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsRoute = AuthTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketParsingRoute = AuthTicketParsingRouteImport.update({
  id: '/ticket-parsing',
  path: '/ticket-parsing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTelegramRoute = AuthTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSituationCenterRoute = AuthSituationCenterRouteImport.update({
  id: '/situation-center',
  path: '/situation-center',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegistrationRoute = AuthRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMyTicketsRoute = AuthMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCodeRepositoryRoute = AuthCodeRepositoryRouteImport.update({
  id: '/code-repository',
  path: '/code-repository',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArmDemoRoute = AuthArmDemoRouteImport.update({
  id: '/arm-demo',
  path: '/arm-demo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArmRoute = AuthArmRouteImport.update({
  id: '/arm',
  path: '/arm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrackerSplatRoute = AuthTrackerSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthTrackerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/arm': typeof AuthArmRoute
  '/arm-demo': typeof AuthArmDemoRoute
  '/code-repository': typeof AuthCodeRepositoryRoute
  '/my-tickets': typeof AuthMyTicketsRoute
  '/profile': typeof AuthProfileRoute
  '/registration': typeof AuthRegistrationRoute
  '/reports': typeof AuthReportsRoute
  '/situation-center': typeof AuthSituationCenterRoute
  '/telegram': typeof AuthTelegramRoute
  '/ticket-parsing': typeof AuthTicketParsingRoute
  '/tickets': typeof AuthTicketsRoute
  '/tools': typeof AuthToolsRoute
  '/tracker': typeof AuthTrackerRouteWithChildren
  '/tracker/$': typeof AuthTrackerSplatRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/arm': typeof AuthArmRoute
  '/arm-demo': typeof AuthArmDemoRoute
  '/code-repository': typeof AuthCodeRepositoryRoute
  '/my-tickets': typeof AuthMyTicketsRoute
  '/profile': typeof AuthProfileRoute
  '/registration': typeof AuthRegistrationRoute
  '/reports': typeof AuthReportsRoute
  '/situation-center': typeof AuthSituationCenterRoute
  '/telegram': typeof AuthTelegramRoute
  '/ticket-parsing': typeof AuthTicketParsingRoute
  '/tickets': typeof AuthTicketsRoute
  '/tools': typeof AuthToolsRoute
  '/tracker': typeof AuthTrackerRouteWithChildren
  '/': typeof AuthIndexRoute
  '/tracker/$': typeof AuthTrackerSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/arm': typeof AuthArmRoute
  '/_auth/arm-demo': typeof AuthArmDemoRoute
  '/_auth/code-repository': typeof AuthCodeRepositoryRoute
  '/_auth/my-tickets': typeof AuthMyTicketsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/registration': typeof AuthRegistrationRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/situation-center': typeof AuthSituationCenterRoute
  '/_auth/telegram': typeof AuthTelegramRoute
  '/_auth/ticket-parsing': typeof AuthTicketParsingRoute
  '/_auth/tickets': typeof AuthTicketsRoute
  '/_auth/tools': typeof AuthToolsRoute
  '/_auth/tracker': typeof AuthTrackerRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/tracker/$': typeof AuthTrackerSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/arm'
    | '/arm-demo'
    | '/code-repository'
    | '/my-tickets'
    | '/profile'
    | '/registration'
    | '/reports'
    | '/situation-center'
    | '/telegram'
    | '/ticket-parsing'
    | '/tickets'
    | '/tools'
    | '/tracker'
    | '/tracker/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/arm'
    | '/arm-demo'
    | '/code-repository'
    | '/my-tickets'
    | '/profile'
    | '/registration'
    | '/reports'
    | '/situation-center'
    | '/telegram'
    | '/ticket-parsing'
    | '/tickets'
    | '/tools'
    | '/tracker'
    | '/'
    | '/tracker/$'
  id:
    | '__root__'
    | '/403'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/analytics'
    | '/_auth/arm'
    | '/_auth/arm-demo'
    | '/_auth/code-repository'
    | '/_auth/my-tickets'
    | '/_auth/profile'
    | '/_auth/registration'
    | '/_auth/reports'
    | '/_auth/situation-center'
    | '/_auth/telegram'
    | '/_auth/ticket-parsing'
    | '/_auth/tickets'
    | '/_auth/tools'
    | '/_auth/tracker'
    | '/_auth/'
    | '/_auth/tracker/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tracker': {
      id: '/_auth/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthTrackerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tools': {
      id: '/_auth/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthToolsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets': {
      id: '/_auth/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ticket-parsing': {
      id: '/_auth/ticket-parsing'
      path: '/ticket-parsing'
      fullPath: '/ticket-parsing'
      preLoaderRoute: typeof AuthTicketParsingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/telegram': {
      id: '/_auth/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AuthTelegramRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/situation-center': {
      id: '/_auth/situation-center'
      path: '/situation-center'
      fullPath: '/situation-center'
      preLoaderRoute: typeof AuthSituationCenterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/registration': {
      id: '/_auth/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthRegistrationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/my-tickets': {
      id: '/_auth/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthMyTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/code-repository': {
      id: '/_auth/code-repository'
      path: '/code-repository'
      fullPath: '/code-repository'
      preLoaderRoute: typeof AuthCodeRepositoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/arm-demo': {
      id: '/_auth/arm-demo'
      path: '/arm-demo'
      fullPath: '/arm-demo'
      preLoaderRoute: typeof AuthArmDemoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/arm': {
      id: '/_auth/arm'
      path: '/arm'
      fullPath: '/arm'
      preLoaderRoute: typeof AuthArmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tracker/$': {
      id: '/_auth/tracker/$'
      path: '/$'
      fullPath: '/tracker/$'
      preLoaderRoute: typeof AuthTrackerSplatRouteImport
      parentRoute: typeof AuthTrackerRoute
    }
  }
}

interface AuthTrackerRouteChildren {
  AuthTrackerSplatRoute: typeof AuthTrackerSplatRoute
}

const AuthTrackerRouteChildren: AuthTrackerRouteChildren = {
  AuthTrackerSplatRoute: AuthTrackerSplatRoute,
}

const AuthTrackerRouteWithChildren = AuthTrackerRoute._addFileChildren(
  AuthTrackerRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthArmRoute: typeof AuthArmRoute
  AuthArmDemoRoute: typeof AuthArmDemoRoute
  AuthCodeRepositoryRoute: typeof AuthCodeRepositoryRoute
  AuthMyTicketsRoute: typeof AuthMyTicketsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthSituationCenterRoute: typeof AuthSituationCenterRoute
  AuthTelegramRoute: typeof AuthTelegramRoute
  AuthTicketParsingRoute: typeof AuthTicketParsingRoute
  AuthTicketsRoute: typeof AuthTicketsRoute
  AuthToolsRoute: typeof AuthToolsRoute
  AuthTrackerRoute: typeof AuthTrackerRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthArmRoute: AuthArmRoute,
  AuthArmDemoRoute: AuthArmDemoRoute,
  AuthCodeRepositoryRoute: AuthCodeRepositoryRoute,
  AuthMyTicketsRoute: AuthMyTicketsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthSituationCenterRoute: AuthSituationCenterRoute,
  AuthTelegramRoute: AuthTelegramRoute,
  AuthTicketParsingRoute: AuthTicketParsingRoute,
  AuthTicketsRoute: AuthTicketsRoute,
  AuthToolsRoute: AuthToolsRoute,
  AuthTrackerRoute: AuthTrackerRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
